import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Page = 'home' | 'customers' | 'products'
type Product = {
  id: number; slug: string; name: string; category: string; target: string; model: string; color: string
  availableColors: string[]; images: string[]; shortDescription: string; description: string; price: string; material: string
  features: string[]; availableSizes: string[]; sandalLength: string; footLengthRecommendation: string
  width?: string | null; wedgeHeight?: string | null; packagingWeight?: string | null; availability: string
}
type Customer = { id: number; name: string; whatsapp: string; created_at: string; province?: string | null }
type ProductForm = Omit<Product, 'id'>

const API_BASE = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api/v1'
const DUMMY_EMAIL = 'admin@crousel.id'
const DUMMY_PASSWORD = 'admin123'
const emptyProduct: ProductForm = { slug: '', name: '', category: 'Sandal Slide Women', target: 'Women', model: '', color: '', availableColors: [], images: [], shortDescription: '', description: '', price: '', material: '', features: [], availableSizes: [], sandalLength: '', footLengthRecommendation: '', width: null, wedgeHeight: null, packagingWeight: null, availability: 'Tersedia' }

async function apiRequest<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = sessionStorage.getItem('admin_api_token') ?? import.meta.env.VITE_API_TOKEN
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { Accept: 'application/json', 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } })
  const payload = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(payload.message ?? `API error (${response.status})`)
  return payload as T
}

function App() {
  const [authenticated, setAuthenticated] = useState(() => sessionStorage.getItem('admin_authenticated') === 'true')
  const [page, setPage] = useState<Page>(() => (window.location.hash.slice(1) as Page) || 'home')
  useEffect(() => { const onHashChange = () => setPage((window.location.hash.slice(1) as Page) || 'home'); window.addEventListener('hashchange', onHashChange); return () => window.removeEventListener('hashchange', onHashChange) }, [])
  const navigate = (nextPage: Page) => { window.location.hash = nextPage }
  const login = () => { sessionStorage.setItem('admin_authenticated', 'true'); setAuthenticated(true); navigate('home') }
  const logout = () => { sessionStorage.removeItem('admin_authenticated'); sessionStorage.removeItem('admin_api_token'); setAuthenticated(false) }
  if (!authenticated) return <LoginPage onLogin={login} />
  return <AdminShell page={page} onNavigate={navigate} onLogout={logout} />
}

function LoginPage({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); if (email.trim().toLowerCase() !== DUMMY_EMAIL || password !== DUMMY_PASSWORD) { setError('Email atau password belum sesuai dengan akun demo.'); return }; onLogin() }
  return <main className="login-page"><div className="login-art" aria-hidden="true"><div className="art-orb orb-one" /><div className="art-orb orb-two" /><p className="art-wordmark">CROUSEL<span>.</span></p><p className="art-caption">YOUR HAPPINESS STUFF</p></div><section className="login-panel"><div className="login-content"><p className="eyebrow">Admin workspace</p><h1>Selamat datang kembali.</h1><p className="muted">Masuk untuk mengelola katalog dan pelanggan Crousel.</p><form onSubmit={submit} className="login-form"><label>Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="admin@crousel.id" /></label><label>Password<input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Masukkan password" /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" type="submit">Masuk ke dashboard <span aria-hidden="true">→</span></button></form><div className="demo-hint"><span className="hint-dot" /> Akun demo: <strong>{DUMMY_EMAIL}</strong> · <strong>{DUMMY_PASSWORD}</strong></div></div></section></main>
}

function AdminShell({ page, onNavigate, onLogout }: { page: Page; onNavigate: (page: Page) => void; onLogout: () => void }) {
  const [mobileSidebar, setMobileSidebar] = useState(false); const nav = (nextPage: Page) => { onNavigate(nextPage); setMobileSidebar(false) }
  return <div className="admin-shell"><aside className={`sidebar ${mobileSidebar ? 'sidebar-open' : ''}`}><div className="sidebar-brand"><span className="brand-mark">C</span><span><strong>CROUSEL</strong><small>Admin workspace</small></span><button className="icon-button sidebar-close" onClick={() => setMobileSidebar(false)} aria-label="Tutup sidebar">×</button></div><p className="nav-label">Workspace</p><nav className="sidebar-nav"><NavItem icon="⌂" label="Home" active={page === 'home'} onClick={() => nav('home')} /><NavItem icon="◎" label="Users / Customer" active={page === 'customers'} onClick={() => nav('customers')} /><NavItem icon="□" label="Produk" active={page === 'products'} onClick={() => nav('products')} /></nav><div className="sidebar-bottom"><div className="admin-mini"><span className="avatar">A</span><span><strong>Admin Crousel</strong><small>Administrator</small></span></div><button className="logout-button" onClick={onLogout}>Keluar <span aria-hidden="true">↗</span></button></div></aside>{mobileSidebar && <button className="sidebar-backdrop" onClick={() => setMobileSidebar(false)} aria-label="Tutup menu" />}<div className="content-shell"><header className="topbar"><button className="menu-toggle" onClick={() => setMobileSidebar(true)} aria-label="Buka menu">☰</button><div><p className="topbar-kicker">Crousel Official</p><p className="topbar-title">{page === 'home' ? 'Overview' : page === 'products' ? 'Product catalogue' : 'Customer directory'}</p></div><div className="topbar-actions"><span className="status-pill"><i /> API workspace</span><span className="topbar-avatar">A</span></div></header><main className="page-content">{page === 'home' && <HomePage onNavigate={onNavigate} />}{page === 'products' && <ProductsPage />}{page === 'customers' && <CustomersPage />}</main></div></div>
}

function NavItem({ icon, label, active, onClick }: { icon: string; label: string; active: boolean; onClick: () => void }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-icon">{icon}</span>{label}<span className="nav-arrow">›</span></button> }
function HomePage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<Customer[]>([])
  useEffect(() => { void Promise.all([apiRequest<{ data: Product[] }>('/products'), apiRequest<{ data: Customer[] }>('/users')]).then(([productData, customerData]) => { setProducts(productData.data); setCustomers(customerData.data) }).catch(() => undefined) }, [])
  return <><div className="page-heading"><div><p className="eyebrow">Monday, 05 September 2026</p><h1>Selamat pagi, Admin.</h1><p className="muted">Pantau katalog dan aktivitas pelanggan dari satu tempat.</p></div><button className="primary-button compact" onClick={() => onNavigate('products')}>Kelola produk <span aria-hidden="true">→</span></button></div><section className="stats-grid"><StatCard label="Total produk" value={products.length ? String(products.length) : '—'} note="Data dari API katalog" tone="yellow" icon="□" /><StatCard label="Customer" value={customers.length ? String(customers.length) : '—'} note="Data dari API user" tone="lavender" icon="◎" /><StatCard label="Status API" value="Online" note="Terhubung ke backend" tone="mint" icon="↗" /></section><section className="dashboard-grid"><div className="panel welcome-panel"><div><p className="eyebrow">Quick start</p><h2>Ruang kerja yang lebih rapi.</h2><p className="muted">Gunakan menu di sidebar untuk mengelola produk dan melihat customer yang tersimpan di database.</p></div><div className="quick-actions"><button onClick={() => onNavigate('products')}><span>□</span><strong>Kelola produk</strong><small>Tambah, ubah, dan hapus katalog</small></button><button onClick={() => onNavigate('customers')}><span>◎</span><strong>Lihat customer</strong><small>Data pelanggan dari API</small></button></div></div><div className="panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Ringkasan</p><h2>API activity</h2></div><span className="live-label"><i /> Live</span></div><div className="activity-row"><span className="activity-icon">✓</span><span><strong>Product endpoint</strong><small>GET /products</small></span><em>Ready</em></div><div className="activity-row"><span className="activity-icon">✓</span><span><strong>Customer endpoint</strong><small>GET /users</small></span><em>Ready</em></div></div></section></>
}
function StatCard({ label, value, note, tone, icon }: { label: string; value: string; note: string; tone: string; icon: string }) { return <article className={`stat-card ${tone}`}><span className="stat-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article> }

function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<Product | null>(null); const [showForm, setShowForm] = useState(false)
  const load = async () => { setLoading(true); try { const result = await apiRequest<{ data: Product[] }>('/products'); setProducts(result.data); setError('') } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Tidak dapat memuat produk.') } finally { setLoading(false) } }
  // Loading remote data is the synchronization this effect is responsible for.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => products.filter((product) => `${product.name} ${product.category}`.toLowerCase().includes(query.toLowerCase())), [products, query])
  const remove = async (product: Product) => { if (!window.confirm(`Hapus ${product.name}?`)) return; try { await apiRequest(`/products/${product.id}`, { method: 'DELETE' }); setProducts((items) => items.filter((item) => item.id !== product.id)); setError('') } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Produk gagal dihapus.') } }
  return <><div className="page-heading"><div><p className="eyebrow">Catalog management</p><h1>Produk</h1><p className="muted">Kelola semua produk yang tampil di katalog Crousel.</p></div><button className="primary-button compact" onClick={() => { setEditing(null); setShowForm(true) }}>+ Tambah produk</button></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama atau kategori..." /></div><button className="outline-button" onClick={() => void load()}>Refresh ↻</button></div>{error && <div className="api-error">{error} <small>Pastikan backend berjalan di {API_BASE}.</small></div>}{loading ? <Loading /> : filtered.length ? <div className="table-scroll"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Target</th><th>Harga</th><th>Status</th><th aria-label="Aksi" /></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><div className="product-cell"><div className="product-thumb">{product.images?.[0] ? <img src={product.images[0]} alt="" /> : <span>□</span>}</div><span><strong>{product.name}</strong><small>{product.slug}</small></span></div></td><td>{product.category}</td><td>{product.target}</td><td className="price-cell">{product.price}</td><td><span className={`availability ${product.availability === 'Tersedia' ? 'available' : ''}`}>{product.availability}</span></td><td><div className="row-actions"><button onClick={() => { setEditing(product); setShowForm(true) }} aria-label={`Edit ${product.name}`}>Edit</button><button className="danger-text" onClick={() => void remove(product)} aria-label={`Hapus ${product.name}`}>Hapus</button></div></td></tr>)}</tbody></table></div> : <EmptyState message="Belum ada produk di database." />}</section>{showForm && <ProductModal product={editing} onClose={() => setShowForm(false)} onSaved={(product) => { setProducts((items) => editing ? items.map((item) => item.id === product.id ? product : item) : [product, ...items]); setShowForm(false) }} />}</>
}

function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void apiRequest<{ data: Customer[] }>('/users').then((result) => setCustomers(result.data)).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Tidak dapat memuat customer.')).finally(() => setLoading(false)) }, [])
  const filtered = customers.filter((customer) => `${customer.name} ${customer.whatsapp}`.toLowerCase().includes(query.toLowerCase()))
  return <><div className="page-heading"><div><p className="eyebrow">Customer directory</p><h1>Users / Customer</h1><p className="muted">Lihat customer yang terdaftar melalui API Crousel.</p></div><span className="count-badge">{customers.length} customer</span></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama atau WhatsApp..." /></div></div>{error && <div className="api-error">{error} <small>Endpoint customer membutuhkan akses API Bearer.</small></div>}{loading ? <Loading /> : filtered.length ? <div className="table-scroll"><table><thead><tr><th>Customer</th><th>WhatsApp</th><th>Provinsi</th><th>Terdaftar</th><th>Status</th></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id}><td><div className="customer-cell"><span className="customer-avatar">{customer.name.charAt(0).toUpperCase()}</span><strong>{customer.name}</strong></div></td><td>{customer.whatsapp}</td><td>{customer.province ?? '—'}</td><td>{new Date(customer.created_at).toLocaleDateString('id-ID')}</td><td><span className="availability available">Aktif</span></td></tr>)}</tbody></table></div> : <EmptyState message="Belum ada customer yang tersimpan." />}</section></>
}

function ProductModal({ product, onClose, onSaved }: { product: Product | null; onClose: () => void; onSaved: (product: Product) => void }) {
  const [form, setForm] = useState<ProductForm>(product ? { ...product, availableColors: product.availableColors ?? [], images: product.images ?? [], features: product.features ?? [], availableSizes: product.availableSizes ?? [] } : emptyProduct); const [error, setError] = useState('')
  const update = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm((current) => ({ ...current, [key]: value })); const text = (key: keyof ProductForm) => Array.isArray(form[key]) ? (form[key] as string[]).join(', ') : String(form[key] ?? '')
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const body = { ...form, availableColors: text('availableColors').split(',').map((item) => item.trim()).filter(Boolean), images: text('images').split(',').map((item) => item.trim()).filter(Boolean), features: text('features').split(',').map((item) => item.trim()).filter(Boolean), availableSizes: text('availableSizes').split(',').map((item) => item.trim()).filter(Boolean) }; try { const result = await apiRequest<{ data: { product: Product } }>(product ? `/products/${product.id}` : '/products', { method: product ? 'PATCH' : 'POST', body: JSON.stringify(body) }); onSaved(result.data.product) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Produk gagal disimpan.') } }
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="product-modal-title"><div className="modal-heading"><div><p className="eyebrow">Catalog</p><h2 id="product-modal-title">{product ? 'Edit produk' : 'Tambah produk'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Tutup">×</button></div><form onSubmit={submit} className="product-form"><div className="form-grid"><Field label="Nama produk" value={form.name} onChange={(value) => update('name', value)} required /><Field label="Slug" value={form.slug} onChange={(value) => update('slug', value)} required /><Field label="Kategori" value={form.category} onChange={(value) => update('category', value)} required /><Field label="Harga" value={form.price} onChange={(value) => update('price', value)} required /><Field label="Model" value={form.model} onChange={(value) => update('model', value)} required /><Field label="Warna utama" value={form.color} onChange={(value) => update('color', value)} required /><SelectField label="Target" value={form.target} options={['Women', 'Men', 'Unisex', 'Kids']} onChange={(value) => update('target', value)} /><SelectField label="Availability" value={form.availability} options={['Tersedia', 'Pre-order', 'Habis']} onChange={(value) => update('availability', value)} /><Field label="Warna tersedia (pisahkan koma)" value={text('availableColors')} onChange={(value) => update('availableColors', value.split(','))} required /><Field label="Ukuran tersedia (pisahkan koma)" value={text('availableSizes')} onChange={(value) => update('availableSizes', value.split(','))} required /><Field label="Gambar URL (pisahkan koma)" value={text('images')} onChange={(value) => update('images', value.split(','))} required /><Field label="Fitur (pisahkan koma)" value={text('features')} onChange={(value) => update('features', value.split(','))} required /><Field label="Panjang sandal" value={form.sandalLength} onChange={(value) => update('sandalLength', value)} required /><Field label="Rekomendasi panjang kaki" value={form.footLengthRecommendation} onChange={(value) => update('footLengthRecommendation', value)} required /><Field label="Material" value={form.material} onChange={(value) => update('material', value)} required /><Field label="Lebar" value={form.width ?? ''} onChange={(value) => update('width', value)} /></div><label>Deskripsi singkat<textarea value={form.shortDescription} onChange={(event) => update('shortDescription', event.target.value)} required rows={2} /></label><label>Deskripsi lengkap<textarea value={form.description} onChange={(event) => update('description', event.target.value)} required rows={3} /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Batal</button><button type="submit" className="primary-button">Simpan produk</button></div></form></section></div>
}
function Field({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label>{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label> }
function Loading() { return <div className="empty-state"><span className="loader" /> Memuat data...</div> }
function EmptyState({ message }: { message: string }) { return <div className="empty-state"><span className="empty-icon">□</span><strong>{message}</strong><small>Data akan muncul setelah tersedia di database.</small></div> }
export default App
